{
 "title": "Channel Statistics",
 "description": "Message statistics and server health of Mirth Connect instances, scraped by the mirth-prometheus-exporter.",
 "tags": [
  "mirth",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "mirthInstance",
    "label": "Instance",
    "query": {
     "query": "label_values(mirth_server_state,exported_instance)"
    }
   },
   {
    "name": "channelName",
    "label": "Channel",
    "query": {
     "query": "label_values(mirth_messages_received_total{exported_instance=~\"$mirthInstance\"},channelName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "${mirthInstance}",
   "type": "stat",
   "description": "Time of the last received message on the selected channels.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "mirthInstance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(mirth_messages_received_total{channelName=~\"$channelName\", exported_instance=~\"$mirthInstance\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$mirthInstance Server Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "mirthInstance" },
  {
   "title": "Server State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirth_server_state{exported_instance=~\"$mirthInstance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mirth Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirth_server_info{exported_instance=~\"$mirthInstance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirth_channels_total{exported_instance=~\"$mirthInstance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel States",
   "type": "stat",
   "description": "Number of deployed channels per state.",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mirth_channel_state{exported_instance=~\"$mirthInstance\", state=\"STARTED\"} == 1) or vector(0)",
     "legendFormat": "Started"
    },
    {
     "expr": "count(mirth_channel_state{exported_instance=~\"$mirthInstance\", state=\"PAUSED\"} == 1) or vector(0)",
     "legendFormat": "Paused"
    },
    {
     "expr": "count(mirth_channel_state{exported_instance=~\"$mirthInstance\", state=\"STOPPED\"} == 1) or vector(0)",
     "legendFormat": "Stopped"
    }
   ]
  },
  {
   "title": "Modified Since Deploy",
   "type": "stat",
   "description": "Channels that have saved revisions which are not deployed yet (deployed revision delta > 0).",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mirth_channel_deployed_revision_delta{exported_instance=~\"$mirthInstance\"} > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "CPU usage as reported by the Mirth API.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mirth_cpu_usage_percent{exported_instance=~\"$mirthInstance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "description": "Used disk space on the Mirth server.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - mirth_disk_free_bytes{exported_instance=~\"$mirthInstance\"} / mirth_disk_total_bytes{exported_instance=~\"$mirthInstance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mirth_memory_allocated_bytes{exported_instance=~\"$mirthInstance\"} - mirth_memory_free_bytes{exported_instance=~\"$mirthInstance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mirth_memory_allocated_bytes{exported_instance=~\"$mirthInstance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "mirth_memory_max_bytes{exported_instance=~\"$mirthInstance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "$mirthInstance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "mirthInstance" },
  {
   "title": "Total Received",
   "type": "stat",
   "description": "Messages received on the selected channels within the dashboard time range.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mirth_messages_received_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sent",
   "type": "stat",
   "description": "Messages sent on the selected channels within the dashboard time range.",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mirth_messages_sent_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Filtered",
   "type": "stat",
   "description": "Messages filtered on the selected channels within the dashboard time range.",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mirth_messages_filtered_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errored",
   "type": "stat",
   "description": "Messages that errored on the selected channels within the dashboard time range.",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mirth_messages_errored_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Queued",
   "type": "stat",
   "description": "Messages currently queued on the selected channels.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mirth_messages_queued{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Message Stats (Over Time)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Received by Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(mirth_messages_received_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__interval]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Received Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "increase(mirth_messages_received_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__rate_interval])",
     "legendFormat": "{{channelName}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Total Sent by Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(mirth_messages_sent_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Sent Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "increase(mirth_messages_sent_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__rate_interval])",
     "legendFormat": "{{channelName}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Total Errored by Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(mirth_messages_errored_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__interval]))",
     "legendFormat": "Errored"
    }
   ]
  },
  {
   "title": "Errored Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "increase(mirth_messages_errored_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__rate_interval])",
     "legendFormat": "{{channelName}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Total Filtered by Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(mirth_messages_filtered_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__interval]))",
     "legendFormat": "Filtered"
    }
   ]
  },
  {
   "title": "Filtered Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 44 },
   "targets": [
    {
     "expr": "increase(mirth_messages_filtered_total{exported_instance=~\"$mirthInstance\", channelName=~\"$channelName\"}[$__rate_interval])",
     "legendFormat": "{{channelName}} ({{exported_instance}})"
    }
   ]
  }
 ]
}